### GET USERS
GET http://localhost:3010/api/users

### GET USER
GET http://localhost:3010/api/users/1

### DELETE USER
DELETE http://localhost:3010/api/users/1


### ADD USER
POST http://localhost:3010/api/users
content-type: application/json

{
  "name": "Vireo alivaceus",
  "email": "vireo@gmail.com",
  "password": "123456",
  "age": 3,
  "height": 0.23,
  "homeTeam": "Coritian"
}


### UPDATE USER
PUT http://localhost:3010/api/users/1
content-type: application/json

{
  "name": "Megarynchus pitangua",
  "email": "pitangua@gmail.com",
  "password": "123456",
  "homeTeam": ""
}


### LOGIN USER
POST http://localhost:3010/api/users/login
content-type: application/json

{
  "email": "pitangua@gmail.com",
  "password": "123456"
}


### AUTH USER
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjEsImVtYWlsIjoicGl0YW5ndWFAZ21haWwuY29tIiwiaWF0IjoxNjMxNzA5ODE2LCJleHAiOjE2MzE3MTE2MTZ9.Bt_5c3HQSJr2BZFfdB3uqWLlHkXGtm-RZe_NnrckYMA

GET http://localhost:3010/api/users/auth
Authorization: Bearer {{token}}


